import type { SubjectCoefficient } from '../../types';

export const mockSubjectCoefficients: SubjectCoefficient[] = [
  // --- Première Année ---
  { id: 'sc_1_tc_1', subject: 'Arabe', level: '1 annee', specialization: 'Tronc Commun', hours: '5', coefficient: '3' },
  { id: 'sc_1_tc_2', subject: 'Français', level: '1 annee', specialization: 'Tronc Commun', hours: '4', coefficient: '2.5' },
  { id: 'sc_1_tc_3', subject: 'Anglais', level: '1 annee', specialization: 'Tronc Commun', hours: '3', coefficient: '1.5' },
  { id: 'sc_1_tc_4', subject: 'Histoire', level: '1 annee', specialization: 'Tronc Commun', hours: '1.5', coefficient: '1.5' },
  { id: 'sc_1_tc_5', subject: 'Géographie', level: '1 annee', specialization: 'Tronc Commun', hours: '1.5', coefficient: '1.5' },
  { id: 'sc_1_tc_6', subject: 'Pensée Islamique', level: '1 annee', specialization: 'Tronc Commun', hours: '1', coefficient: '1' },
  { id: 'sc_1_tc_7', subject: 'Education Civile', level: '1 annee', specialization: 'Tronc Commun', hours: '1', coefficient: '1' },
  { id: 'sc_1_tc_8', subject: 'Mathématiques', level: '1 annee', specialization: 'Tronc Commun', hours: '4', coefficient: '3' },
  { id: 'sc_1_tc_9', subject: 'Physique', level: '1 annee', specialization: 'Tronc Commun', hours: '3', coefficient: '2.5' },
  { id: 'sc_1_tc_10', subject: 'Sciences de la Vie et de la Terre', level: '1 annee', specialization: 'Tronc Commun', hours: '2', coefficient: '1.5' },
  { id: 'sc_1_tc_11', subject: 'Technologie', level: '1 annee', specialization: 'Tronc Commun', hours: '2', coefficient: '1' },
  { id: 'sc_1_tc_12', subject: 'Informatique', level: '1 annee', specialization: 'Tronc Commun', hours: '2', coefficient: '1' },
  { id: 'sc_1_tc_13', subject: 'Sport', level: '1 annee', specialization: 'Tronc Commun', hours: '2', coefficient: '1' },
  { id: 'sc_1_tc_14', subject: 'Arts', level: '1 annee', specialization: 'Tronc Commun', hours: '2', coefficient: '1' },
  { id: 'sc_1_tc_15', subject: 'Projet', level: '1 annee', specialization: 'Tronc Commun', hours: '1', coefficient: '1' },

  // --- Deuxième Année ---
  // Lettres
  { id: 'sc_2_l_1', subject: 'Arabe', level: '2 annee', specialization: 'Lettres', hours: '5', coefficient: '4' },
  { id: 'sc_2_l_2', subject: 'Français', level: '2 annee', specialization: 'Lettres', hours: '4', coefficient: '3' },
  { id: 'sc_2_l_3', subject: 'Anglais', level: '2 annee', specialization: 'Lettres', hours: '3', coefficient: '1.5' },
  { id: 'sc_2_l_4', subject: 'Histoire', level: '2 annee', specialization: 'Lettres', hours: '1.5', coefficient: '1.5' },
  { id: 'sc_2_l_5', subject: 'Géographie', level: '2 annee', specialization: 'Lettres', hours: '1.5', coefficient: '1.5' },
  { id: 'sc_2_l_6', subject: 'Pensée Islamique', level: '2 annee', specialization: 'Lettres', hours: '1', coefficient: '1' },
  { id: 'sc_2_l_7', subject: 'Education Civile', level: '2 annee', specialization: 'Lettres', hours: '1', coefficient: '1' },
  { id: 'sc_2_l_8', subject: 'Philosophie', level: '2 annee', specialization: 'Lettres', hours: '3', coefficient: '1' },
  { id: 'sc_2_l_9', subject: 'Mathématiques', level: '2 annee', specialization: 'Lettres', hours: '2', coefficient: '1' },
  { id: 'sc_2_l_10', subject: 'Informatique', level: '2 annee', specialization: 'Lettres', hours: '2', coefficient: '1' },
  { id: 'sc_2_l_11', subject: 'Sport', level: '2 annee', specialization: 'Lettres', hours: '2', coefficient: '1' },
  // Économie et Services
  { id: 'sc_2_es_1', subject: 'Arabe', level: '2 annee', specialization: 'Économie et Services', hours: '2', coefficient: '2' },
  { id: 'sc_2_es_2', subject: 'Français', level: '2 annee', specialization: 'Économie et Services', hours: '3', coefficient: '2' },
  { id: 'sc_2_es_3', subject: 'Anglais', level: '2 annee', specialization: 'Économie et Services', hours: '3', coefficient: '1.5' },
  { id: 'sc_2_es_4', subject: 'Histoire', level: '2 annee', specialization: 'Économie et Services', hours: '1.5', coefficient: '1.5' },
  { id: 'sc_2_es_5', subject: 'Géographie', level: '2 annee', specialization: 'Économie et Services', hours: '1.5', coefficient: '1.5' },
  { id: 'sc_2_es_6', subject: 'Pensée Islamique', level: '2 annee', specialization: 'Économie et Services', hours: '1', coefficient: '1' },
  { id: 'sc_2_es_7', subject: 'Education Civile', level: '2 annee', specialization: 'Économie et Services', hours: '1', coefficient: '1' },
  { id: 'sc_2_es_8', subject: 'Economie', level: '2 annee', specialization: 'Économie et Services', hours: '3', coefficient: '3' },
  { id: 'sc_2_es_9', subject: 'Gestion', level: '2 annee', specialization: 'Économie et Services', hours: '3', coefficient: '3' },
  { id: 'sc_2_es_10', subject: 'Mathématiques', level: '2 annee', specialization: 'Économie et Services', hours: '3', coefficient: '2.5' },
  { id: 'sc_2_es_11', subject: 'Informatique', level: '2 annee', specialization: 'Économie et Services', hours: '2', coefficient: '1' },
  { id: 'sc_2_es_12', subject: 'Sport', level: '2 annee', specialization: 'Économie et Services', hours: '2', coefficient: '1' },
  // Technologie de l'Informatique
  { id: 'sc_2_ti_1', subject: 'Arabe', level: '2 annee', specialization: 'Technologie de l\'Informatique', hours: '2', coefficient: '2' },
  { id: 'sc_2_ti_2', subject: 'Français', level: '2 annee', specialization: 'Technologie de l\'Informatique', hours: '2', coefficient: '2' },
  { id: 'sc_2_ti_3', subject: 'Anglais', level: '2 annee', specialization: 'Technologie de l\'Informatique', hours: '2', coefficient: '1' },
  { id: 'sc_2_ti_4', subject: 'Pensée Islamique', level: '2 annee', specialization: 'Technologie de l\'Informatique', hours: '1', coefficient: '1' },
  { id: 'sc_2_ti_5', subject: 'Education Civile', level: '2 annee', specialization: 'Technologie de l\'Informatique', hours: '1', coefficient: '1' },
  { id: 'sc_2_ti_6', subject: 'Mathématiques', level: '2 annee', specialization: 'Technologie de l\'Informatique', hours: '4', coefficient: '4' },
  { id: 'sc_2_ti_7', subject: 'Physique', level: '2 annee', specialization: 'Technologie de l\'Informatique', hours: '3', coefficient: '3' },
  { id: 'sc_2_ti_8', subject: 'Technologie', level: '2 annee', specialization: 'Technologie de l\'Informatique', hours: '2', coefficient: '2' },
  { id: 'sc_2_ti_9', subject: 'Informatique', level: '2 annee', specialization: 'Technologie de l\'Informatique', hours: '5', coefficient: '3' },
  { id: 'sc_2_ti_10', subject: 'Sport', level: '2 annee', specialization: 'Technologie de l\'Informatique', hours: '2', coefficient: '1' },
  // Sciences
  { id: 'sc_2_s_1', subject: 'Arabe', level: '2 annee', specialization: 'Sciences', hours: '2', coefficient: '2' },
  { id: 'sc_2_s_2', subject: 'Français', level: '2 annee', specialization: 'Sciences', hours: '2', coefficient: '2' },
  { id: 'sc_2_s_3', subject: 'Anglais', level: '2 annee', specialization: 'Sciences', hours: '2', coefficient: '1' },
  { id: 'sc_2_s_4', subject: 'Histoire', level: '2 annee', specialization: 'Sciences', hours: '1', coefficient: '1' },
  { id: 'sc_2_s_5', subject: 'Géographie', level: '2 annee', specialization: 'Sciences', hours: '1', coefficient: '1' },
  { id: 'sc_2_s_6', subject: 'Pensée Islamique', level: '2 annee', specialization: 'Sciences', hours: '1', coefficient: '1' },
  { id: 'sc_2_s_7', subject: 'Education Civile', level: '2 annee', specialization: 'Sciences', hours: '1', coefficient: '1' },
  { id: 'sc_2_s_8', subject: 'Mathématiques', level: '2 annee', specialization: 'Sciences', hours: '5', coefficient: '4' },
  { id: 'sc_2_s_9', subject: 'Physique', level: '2 annee', specialization: 'Sciences', hours: '4', coefficient: '3' },
  { id: 'sc_2_s_10', subject: 'Sciences de la Vie et de la Terre', level: '2 annee', specialization: 'Sciences', hours: '3.5', coefficient: '2' },
  { id: 'sc_2_s_13', subject: 'Technologie', level: '2 annee', specialization: 'Sciences', hours: '2', coefficient: '2' },
  { id: 'sc_2_s_11', subject: 'Informatique', level: '2 annee', specialization: 'Sciences', hours: '2', coefficient: '1' },
  { id: 'sc_2_s_12', subject: 'Sport', level: '2 annee', specialization: 'Sciences', hours: '2', coefficient: '1' },

  // --- Troisième Année ---
  // Lettres
  { id: 'sc_3_l_1', subject: 'Arabe', level: '3 annee', specialization: 'Lettres', hours: '5', coefficient: '4' },
  { id: 'sc_3_l_2', subject: 'Français', level: '3 annee', specialization: 'Lettres', hours: '4', coefficient: '3' },
  { id: 'sc_3_l_3', subject: 'Anglais', level: '3 annee', specialization: 'Lettres', hours: '3', coefficient: '2' },
  { id: 'sc_3_l_4', subject: 'Histoire', level: '3 annee', specialization: 'Lettres', hours: '1.5', coefficient: '1.5' },
  { id: 'sc_3_l_5', subject: 'Géographie', level: '3 annee', specialization: 'Lettres', hours: '1.5', coefficient: '1.5' },
  { id: 'sc_3_l_6', subject: 'Pensée Islamique', level: '3 annee', specialization: 'Lettres', hours: '1', coefficient: '1' },
  { id: 'sc_3_l_7', subject: 'Philosophie', level: '3 annee', specialization: 'Lettres', hours: '3', coefficient: '2' },
  { id: 'sc_3_l_8', subject: 'Mathématiques', level: '3 annee', specialization: 'Lettres', hours: '1', coefficient: '1' },
  { id: 'sc_3_l_9', subject: 'Informatique', level: '3 annee', specialization: 'Lettres', hours: '2', coefficient: '1' },
  { id: 'sc_3_l_10', subject: 'Sport', level: '3 annee', specialization: 'Lettres', hours: '2', coefficient: '1' },
  // Économie et Gestion
  { id: 'sc_3_eg_1', subject: 'Arabe', level: '3 annee', specialization: 'Économie et Gestion', hours: '2', coefficient: '1' },
  { id: 'sc_3_eg_2', subject: 'Français', level: '3 annee', specialization: 'Économie et Gestion', hours: '3', coefficient: '2' },
  { id: 'sc_3_eg_3', subject: 'Anglais', level: '3 annee', specialization: 'Économie et Gestion', hours: '3', coefficient: '2' },
  { id: 'sc_3_eg_4', subject: 'Histoire', level: '3 annee', specialization: 'Économie et Gestion', hours: '1.5', coefficient: '1.5' },
  { id: 'sc_3_eg_5', subject: 'Géographie', level: '3 annee', specialization: 'Économie et Gestion', hours: '1.5', coefficient: '1.5' },
  { id: 'sc_3_eg_6', subject: 'Pensée Islamique', level: '3 annee', specialization: 'Économie et Gestion', hours: '1', coefficient: '1' },
  { id: 'sc_3_eg_7', subject: 'Philosophie', level: '3 annee', specialization: 'Économie et Gestion', hours: '1', coefficient: '1' },
  { id: 'sc_3_eg_8', subject: 'Economie', level: '3 annee', specialization: 'Économie et Gestion', hours: '4', coefficient: '3' },
  { id: 'sc_3_eg_9', subject: 'Gestion', level: '3 annee', specialization: 'Économie et Gestion', hours: '4', coefficient: '3' },
  { id: 'sc_3_eg_10', subject: 'Mathématiques', level: '3 annee', specialization: 'Économie et Gestion', hours: '2.5', coefficient: '2.5' },
  { id: 'sc_3_eg_11', subject: 'Informatique', level: '3 annee', specialization: 'Économie et Gestion', hours: '2', coefficient: '1' },
  { id: 'sc_3_eg_12', subject: 'Sport', level: '3 annee', specialization: 'Économie et Gestion', hours: '2', coefficient: '1' },
  // Sciences de l'Informatique
  { id: 'sc_3_si_1', subject: 'Arabe', level: '3 annee', specialization: 'Sciences de l\'Informatique', hours: '2', coefficient: '1' },
  { id: 'sc_3_si_2', subject: 'Français', level: '3 annee', specialization: 'Sciences de l\'Informatique', hours: '2', coefficient: '1' },
  { id: 'sc_3_si_3', subject: 'Anglais', level: '3 annee', specialization: 'Sciences de l\'Informatique', hours: '2', coefficient: '1' },
  { id: 'sc_3_si_4', subject: 'Pensée Islamique', level: '3 annee', specialization: 'Sciences de l\'Informatique', hours: '1', coefficient: '1' },
  { id: 'sc_3_si_5', subject: 'Philosophie', level: '3 annee', specialization: 'Sciences de l\'Informatique', hours: '1', coefficient: '1' },
  { id: 'sc_3_si_6', subject: 'Mathématiques', level: '3 annee', specialization: 'Sciences de l\'Informatique', hours: '5', coefficient: '4' },
  { id: 'sc_3_si_7', subject: 'Physique', level: '3 annee', specialization: 'Sciences de l\'Informatique', hours: '4', coefficient: '3' },
  { id: 'sc_3_si_8', subject: 'Algorithmique & Programmation', level: '3 annee', specialization: 'Sciences de l\'Informatique', hours: '3', coefficient: '3' },
  { id: 'sc_3_si_9', subject: 'Systèmes & Réseaux', level: '3 annee', specialization: 'Sciences de l\'Informatique', hours: '1.5', coefficient: '1.5' },
  { id: 'sc_3_si_10', subject: 'Bases de données', level: '3 annee', specialization: 'Sciences de l\'Informatique', hours: '2', coefficient: '1.5' },
  { id: 'sc_3_si_11', subject: 'Sport', level: '3 annee', specialization: 'Sciences de l\'Informatique', hours: '2', coefficient: '1' },
  // Sciences Techniques
  { id: 'sc_3_st_1', subject: 'Arabe', level: '3 annee', specialization: 'Sciences Techniques', hours: '2', coefficient: '1' },
  { id: 'sc_3_st_2', subject: 'Français', level: '3 annee', specialization: 'Sciences Techniques', hours: '2', coefficient: '1' },
  { id: 'sc_3_st_3', subject: 'Anglais', level: '3 annee', specialization: 'Sciences Techniques', hours: '2', coefficient: '1' },
  { id: 'sc_3_st_4', subject: 'Pensée Islamique', level: '3 annee', specialization: 'Sciences Techniques', hours: '1', coefficient: '1' },
  { id: 'sc_3_st_5', subject: 'Philosophie', level: '3 annee', specialization: 'Sciences Techniques', hours: '1', coefficient: '1' },
  { id: 'sc_3_st_6', subject: 'Mathématiques', level: '3 annee', specialization: 'Sciences Techniques', hours: '5', coefficient: '4' },
  { id: 'sc_3_st_7', subject: 'Physique', level: '3 annee', specialization: 'Sciences Techniques', hours: '5', coefficient: '4' },
  { id: 'sc_3_st_8', subject: 'Technologie', level: '3 annee', specialization: 'Sciences Techniques', hours: '5', coefficient: '4' },
  { id: 'sc_3_st_9', subject: 'Informatique', level: '3 annee', specialization: 'Sciences Techniques', hours: '2', coefficient: '1' },
  { id: 'sc_3_st_10', subject: 'Sport', level: '3 annee', specialization: 'Sciences Techniques', hours: '2', coefficient: '1' },
  // Sciences Expérimentales
  { id: 'sc_3_se_1', subject: 'Arabe', level: '3 annee', specialization: 'Sciences Expérimentales', hours: '2', coefficient: '1' },
  { id: 'sc_3_se_2', subject: 'Français', level: '3 annee', specialization: 'Sciences Expérimentales', hours: '2', coefficient: '1' },
  { id: 'sc_3_se_3', subject: 'Anglais', level: '3 annee', specialization: 'Sciences Expérimentales', hours: '2', coefficient: '1' },
  { id: 'sc_3_se_4', subject: 'Pensée Islamique', level: '3 annee', specialization: 'Sciences Expérimentales', hours: '1', coefficient: '1' },
  { id: 'sc_3_se_5', subject: 'Philosophie', level: '3 annee', specialization: 'Sciences Expérimentales', hours: '1', coefficient: '1' },
  { id: 'sc_3_se_6', subject: 'Mathématiques', level: '3 annee', specialization: 'Sciences Expérimentales', hours: '4', coefficient: '3' },
  { id: 'sc_3_se_7', subject: 'Physique', level: '3 annee', specialization: 'Sciences Expérimentales', hours: '4', coefficient: '3' },
  { id: 'sc_3_se_8', subject: 'Sciences de la Vie et de la Terre', level: '3 annee', specialization: 'Sciences Expérimentales', hours: '4', coefficient: '4' },
  { id: 'sc_3_se_9', subject: 'Sport', level: '3 annee', specialization: 'Sciences Expérimentales', hours: '2', coefficient: '1' },
  // Mathématiques
  { id: 'sc_3_m_1', subject: 'Arabe', level: '3 annee', specialization: 'Mathématiques', hours: '2', coefficient: '1' },
  { id: 'sc_3_m_2', subject: 'Français', level: '3 annee', specialization: 'Mathématiques', hours: '2', coefficient: '1' },
  { id: 'sc_3_m_3', subject: 'Anglais', level: '3 annee', specialization: 'Mathématiques', hours: '2', coefficient: '1' },
  { id: 'sc_3_m_4', subject: 'Pensée Islamique', level: '3 annee', specialization: 'Mathématiques', hours: '1', coefficient: '1' },
  { id: 'sc_3_m_5', subject: 'Philosophie', level: '3 annee', specialization: 'Mathématiques', hours: '1', coefficient: '1' },
  { id: 'sc_3_m_6', subject: 'Mathématiques', level: '3 annee', specialization: 'Mathématiques', hours: '7', coefficient: '4' },
  { id: 'sc_3_m_7', subject: 'Physique', level: '3 annee', specialization: 'Mathématiques', hours: '5', coefficient: '4' },
  { id: 'sc_3_m_8', subject: 'Sciences de la Vie et de la Terre', level: '3 annee', specialization: 'Mathématiques', hours: '1.5', coefficient: '1' },
  { id: 'sc_3_m_9', subject: 'Algorithmique & Programmation', level: '3 annee', specialization: 'Mathématiques', hours: '2', coefficient: '1.5' },
  { id: 'sc_3_m_10', subject: 'Sport', level: '3 annee', specialization: 'Mathématiques', hours: '2', coefficient: '1' },

  // --- Quatrième Année ---
  // Lettres
  { id: 'sc_4_l_1', subject: 'Arabe', level: '4 annee', specialization: 'Lettres', hours: '5', coefficient: '4' },
  { id: 'sc_4_l_2', subject: 'Français', level: '4 annee', specialization: 'Lettres', hours: '4', coefficient: '2' },
  { id: 'sc_4_l_3', subject: 'Anglais', level: '4 annee', specialization: 'Lettres', hours: '3', coefficient: '2' },
  { id: 'sc_4_l_4', subject: 'Histoire', level: '4 annee', specialization: 'Lettres', hours: '2', coefficient: '1' },
  { id: 'sc_4_l_5', subject: 'Géographie', level: '4 annee', specialization: 'Lettres', hours: '2', coefficient: '1' },
  { id: 'sc_4_l_6', subject: 'Pensée Islamique', level: '4 annee', specialization: 'Lettres', hours: '1', coefficient: '1' },
  { id: 'sc_4_l_7', subject: 'Philosophie', level: '4 annee', specialization: 'Lettres', hours: '5', coefficient: '4' },
  { id: 'sc_4_l_8', subject: 'Informatique', level: '4 annee', specialization: 'Lettres', hours: '2', coefficient: '1' },
  { id: 'sc_4_l_9', subject: 'Sport', level: '4 annee', specialization: 'Lettres', hours: '2', coefficient: '1' },
  // Economie et Gestion
  { id: 'sc_4_eg_1', subject: 'Arabe', level: '4 annee', specialization: 'Économie et Gestion', hours: '2', coefficient: '1' },
  { id: 'sc_4_eg_2', subject: 'Français', level: '4 annee', specialization: 'Économie et Gestion', hours: '2', coefficient: '1' },
  { id: 'sc_4_eg_3', subject: 'Anglais', level: '4 annee', specialization: 'Économie et Gestion', hours: '3', coefficient: '1' },
  { id: 'sc_4_eg_4', subject: 'Histoire', level: '4 annee', specialization: 'Économie et Gestion', hours: '2', coefficient: '1' },
  { id: 'sc_4_eg_5', subject: 'Géographie', level: '4 annee', specialization: 'Économie et Gestion', hours: '2', coefficient: '1' },
  { id: 'sc_4_eg_6', subject: 'Pensée Islamique', level: '4 annee', specialization: 'Économie et Gestion', hours: '1', coefficient: '1' },
  { id: 'sc_4_eg_7', subject: 'Philosophie', level: '4 annee', specialization: 'Économie et Gestion', hours: '1', coefficient: '1' },
  { id: 'sc_4_eg_8', subject: 'Economie', level: '4 annee', specialization: 'Économie et Gestion', hours: '5', coefficient: '4' },
  { id: 'sc_4_eg_9', subject: 'Gestion', level: '4 annee', specialization: 'Économie et Gestion', hours: '5', coefficient: '4' },
  { id: 'sc_4_eg_10', subject: 'Mathématiques', level: '4 annee', specialization: 'Économie et Gestion', hours: '2.5', coefficient: '2' },
  { id: 'sc_4_eg_11', subject: 'Informatique', level: '4 annee', specialization: 'Économie et Gestion', hours: '2', coefficient: '1' },
  { id: 'sc_4_eg_12', subject: 'Sport', level: '4 annee', specialization: 'Économie et Gestion', hours: '2', coefficient: '1' },
  // Sciences de l'Informatique
  { id: 'sc_4_si_1', subject: 'Arabe', level: '4 annee', specialization: 'Sciences de l\'Informatique', hours: '2', coefficient: '1' },
  { id: 'sc_4_si_2', subject: 'Français', level: '4 annee', specialization: 'Sciences de l\'Informatique', hours: '2', coefficient: '1' },
  { id: 'sc_4_si_3', subject: 'Anglais', level: '4 annee', specialization: 'Sciences de l\'Informatique', hours: '2', coefficient: '1' },
  { id: 'sc_4_si_4', subject: 'Pensée Islamique', level: '4 annee', specialization: 'Sciences de l\'Informatique', hours: '1', coefficient: '1' },
  { id: 'sc_4_si_5', subject: 'Philosophie', level: '4 annee', specialization: 'Sciences de l\'Informatique', hours: '2', coefficient: '1' },
  { id: 'sc_4_si_6', subject: 'Mathématiques', level: '4 annee', specialization: 'Sciences de l\'Informatique', hours: '4', coefficient: '3' },
  { id: 'sc_4_si_7', subject: 'Physique', level: '4 annee', specialization: 'Sciences de l\'Informatique', hours: '4', coefficient: '2.5' },
  { id: 'sc_4_si_8', subject: 'Tech-Inf-comm (TIC)', level: '4 annee', specialization: 'Sciences de l\'Informatique', hours: '2', coefficient: '1.5' },
  { id: 'sc_4_si_9', subject: 'Systèmes & Réseaux', level: '4 annee', specialization: 'Sciences de l\'Informatique', hours: '2', coefficient: '1.5' },
  { id: 'sc_4_si_10', subject: 'Bases de données', level: '4 annee', specialization: 'Sciences de l\'Informatique', hours: '3', coefficient: '4' },
  { id: 'sc_4_si_11', subject: 'Sport', level: '4 annee', specialization: 'Sciences de l\'Informatique', hours: '2', coefficient: '1' },
  // Sciences Techniques
  { id: 'sc_4_st_1', subject: 'Arabe', level: '4 annee', specialization: 'Sciences Techniques', hours: '2', coefficient: '1' },
  { id: 'sc_4_st_2', subject: 'Français', level: '4 annee', specialization: 'Sciences Techniques', hours: '2', coefficient: '1' },
  { id: 'sc_4_st_3', subject: 'Anglais', level: '4 annee', specialization: 'Sciences Techniques', hours: '2', coefficient: '1' },
  { id: 'sc_4_st_4', subject: 'Pensée Islamique', level: '4 annee', specialization: 'Sciences Techniques', hours: '1', coefficient: '1' },
  { id: 'sc_4_st_5', subject: 'Philosophie', level: '4 annee', specialization: 'Sciences Techniques', hours: '2', coefficient: '1' },
  { id: 'sc_4_st_6', subject: 'Mathématiques', level: '4 annee', specialization: 'Sciences Techniques', hours: '5', coefficient: '3' },
  { id: 'sc_4_st_7', subject: 'Physique', level: '4 annee', specialization: 'Sciences Techniques', hours: '5', coefficient: '3.5' },
  { id: 'sc_4_st_8', subject: 'Technologie', level: '4 annee', specialization: 'Sciences Techniques', hours: '5', coefficient: '4' },
  { id: 'sc_4_st_9', subject: 'Informatique', level: '4 annee', specialization: 'Sciences Techniques', hours: '2', coefficient: '1' },
  { id: 'sc_4_st_10', subject: 'Sport', level: '4 annee', specialization: 'Sciences Techniques', hours: '2', coefficient: '1' },
  // Sciences Expérimentales
  { id: 'sc_4_se_1', subject: 'Arabe', level: '4 annee', specialization: 'Sciences Expérimentales', hours: '2', coefficient: '1' },
  { id: 'sc_4_se_2', subject: 'Français', level: '4 annee', specialization: 'Sciences Expérimentales', hours: '2', coefficient: '1' },
  { id: 'sc_4_se_3', subject: 'Anglais', level: '4 annee', specialization: 'Sciences Expérimentales', hours: '2', coefficient: '1' },
  { id: 'sc_4_se_4', subject: 'Pensée Islamique', level: '4 annee', specialization: 'Sciences Expérimentales', hours: '1', coefficient: '1' },
  { id: 'sc_4_se_5', subject: 'Philosophie', level: '4 annee', specialization: 'Sciences Expérimentales', hours: '1', coefficient: '1' },
  { id: 'sc_4_se_6', subject: 'Mathématiques', level: '4 annee', specialization: 'Sciences Expérimentales', hours: '3', coefficient: '3' },
  { id: 'sc_4_se_7', subject: 'Physique', level: '4 annee', specialization: 'Sciences Expérimentales', hours: '4', coefficient: '3' },
  { id: 'sc_4_se_8', subject: 'Sciences de la Vie et de la Terre', level: '4 annee', specialization: 'Sciences Expérimentales', hours: '8', coefficient: '4' },
  { id: 'sc_4_se_9', subject: 'Sport', level: '4 annee', specialization: 'Sciences Expérimentales', hours: '2', coefficient: '1' },
  // Mathématiques
  { id: 'sc_4_m_1', subject: 'Arabe', level: '4 annee', specialization: 'Mathématiques', hours: '2', coefficient: '1' },
  { id: 'sc_4_m_2', subject: 'Français', level: '4 annee', specialization: 'Mathématiques', hours: '2', coefficient: '1' },
  { id: 'sc_4_m_3', subject: 'Anglais', level: '4 annee', specialization: 'Mathématiques', hours: '2', coefficient: '1' },
  { id: 'sc_4_m_4', subject: 'Pensée Islamique', level: '4 annee', specialization: 'Mathématiques', hours: '1', coefficient: '1' },
  { id: 'sc_4_m_5', subject: 'Philosophie', level: '4 annee', specialization: 'Mathématiques', hours: '2', coefficient: '1' },
  { id: 'sc_4_m_6', subject: 'Mathématiques', level: '4 annee', specialization: 'Mathématiques', hours: '7', coefficient: '4' },
  { id: 'sc_4_m_7', subject: 'Physique', level: '4 annee', specialization: 'Mathématiques', hours: '5', coefficient: '3' },
  { id: 'sc_4_m_8', subject: 'Sciences de la Vie et de la Terre', level: '4 annee', specialization: 'Mathématiques', hours: '1.5', coefficient: '1' },
  { id: 'sc_4_m_9', subject: 'Informatique', level: '4 annee', specialization: 'Mathématiques', hours: '2', coefficient: '1' },
  { id: 'sc_4_m_10', subject: 'Sport', level: '4 annee', specialization: 'Mathématiques', hours: '2', coefficient: '1' },
];